default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "docker.yml"
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.13
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
        exclude: ".*cookiecutter.project_name.*"
      # Run the formatter.
      - id: ruff-format
        exclude: ".*cookiecutter.project_name.*"

### Extra lines below are preserved ###
