name: docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: docker
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: {% raw %}${{ github.ref == 'refs/heads/main' }}{% endraw %}
          tags: ghcr.io/nens/{{ cookiecutter.project_name }}:main
